/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SwingForm;

import DBconfig.DBConnect;
import PanelForm.ClassManager;
import PanelForm.PasswdChange;
import PanelForm.StudentManager;
import PanelForm.UserManager;
import java.awt.Color;
import java.awt.GridLayout;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class MainFormSwing extends javax.swing.JFrame {

    /**
     * Creates new form QLproducts
     */
    public static String UsernameString;
    public MainFormSwing(String UsernameString, boolean UserIsAdmin) {
        initComponents();
        MainFormSwing.UsernameString = UsernameString;
        usernamelabel.setText(MainFormSwing.UsernameString);
        UserManagerMenuBtn.setEnabled(UserIsAdmin);
        UserManagerMenuBtn.setVisible(UserIsAdmin);
        if(UserIsAdmin){
            userRoleLabel.setText("Quản trị viên(Admin)");
        }else{
            userRoleLabel.setText("Người dùng(User)");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContainerPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        userRoleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HeaderNav = new javax.swing.JMenuBar();
        SystemMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        UserManagerMenuBtn = new javax.swing.JMenuItem();
        ChangePassMenuBtn = new javax.swing.JMenuItem();
        ExitBtn = new javax.swing.JMenuItem();
        ManageMenu = new javax.swing.JMenu();
        StudentManagerBtn = new javax.swing.JMenuItem();
        ClassManagerBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(900, 675));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ContainerPanel.setAutoscrolls(true);
        ContainerPanel.setPreferredSize(new java.awt.Dimension(900, 500));

        javax.swing.GroupLayout ContainerPanelLayout = new javax.swing.GroupLayout(ContainerPanel);
        ContainerPanel.setLayout(ContainerPanelLayout);
        ContainerPanelLayout.setHorizontalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        ContainerPanelLayout.setVerticalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        HeaderPanel.setBackground(new java.awt.Color(199, 236, 238));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(900, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("User:");

        usernamelabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        usernamelabel.setText("username");

        userRoleLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        userRoleLabel.setText("Rolename");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Quyền:");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernamelabel)
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userRoleLabel)
                .addGap(52, 52, 52))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(userRoleLabel))
                    .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(usernamelabel)))
                .addContainerGap())
        );

        HeaderNav.setBackground(new java.awt.Color(102, 102, 102));
        HeaderNav.setMargin(new java.awt.Insets(0, 16, 0, 16));
        HeaderNav.setMinimumSize(new java.awt.Dimension(136, 36));
        HeaderNav.setPreferredSize(new java.awt.Dimension(136, 36));

        SystemMenu.setBackground(new java.awt.Color(153, 153, 153));
        SystemMenu.setForeground(new java.awt.Color(255, 255, 255));
        SystemMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/preferences_system-16.png"))); // NOI18N
        SystemMenu.setText("Hệ thống");
        SystemMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        SystemMenu.setMargin(new java.awt.Insets(0, 48, 0, 48));

        jMenu1.setText("jMenu1");
        SystemMenu.add(jMenu1);

        UserManagerMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        UserManagerMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/account-icon-16.png"))); // NOI18N
        UserManagerMenuBtn.setText("Quản lý người dùng");
        UserManagerMenuBtn.setMargin(new java.awt.Insets(0, 24, 0, 24));
        UserManagerMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManagerMenuBtnActionPerformed(evt);
            }
        });
        SystemMenu.add(UserManagerMenuBtn);

        ChangePassMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ChangePassMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/key-icon-16.png"))); // NOI18N
        ChangePassMenuBtn.setText("Đổi mật khẩu");
        ChangePassMenuBtn.setMargin(new java.awt.Insets(0, 24, 0, 24));
        ChangePassMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassMenuBtnActionPerformed(evt);
            }
        });
        SystemMenu.add(ChangePassMenuBtn);

        ExitBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit-icon-16.png"))); // NOI18N
        ExitBtn.setText("Thoát");
        ExitBtn.setMargin(new java.awt.Insets(0, 24, 0, 24));
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        SystemMenu.add(ExitBtn);

        ManageMenu.setBackground(new java.awt.Color(153, 153, 153));
        ManageMenu.setForeground(new java.awt.Color(255, 255, 255));
        ManageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/manage-icon-16.png"))); // NOI18N
        ManageMenu.setText("Quản lý");
        ManageMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ManageMenu.setMargin(new java.awt.Insets(0, 48, 0, 48));

        StudentManagerBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        StudentManagerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/female-student-icon-16.png"))); // NOI18N
        StudentManagerBtn.setText("Thông tin học sinh");
        StudentManagerBtn.setMargin(new java.awt.Insets(0, 24, 0, 24));
        StudentManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentManagerBtnActionPerformed(evt);
            }
        });
        ManageMenu.add(StudentManagerBtn);

        ClassManagerBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ClassManagerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/classroom-icon-16.png"))); // NOI18N
        ClassManagerBtn.setText("Thông tin lớp học");
        ClassManagerBtn.setMargin(new java.awt.Insets(0, 24, 0, 24));
        ClassManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassManagerBtnActionPerformed(evt);
            }
        });
        ManageMenu.add(ClassManagerBtn);

        SystemMenu.add(ManageMenu);

        HeaderNav.add(SystemMenu);

        setJMenuBar(HeaderNav);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContainerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void FillTable(JTable table, String MysqltableName) throws ClassNotFoundException, SQLException
    {
        DBConnect conn = new DBConnect();
        ResultSet rs = conn.getData(MysqltableName);
        while(table.getRowCount() > 0) 
        {
            //JOptionPane.showMessageDialog(null, table.getRowCount());
            ((DefaultTableModel) table.getModel()).setRowCount(0);
            //((DefaultTableModel) table.getModel()).removeRow(0);
        }
        int columns = rs.getMetaData().getColumnCount();
        while(rs.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                row[i - 1] = rs.getObject(i);
            }
            ((DefaultTableModel) table.getModel()).insertRow(rs.getRow()-1,row);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
    JPanel ContentFrame = null;
    private void ShowChildPanel(JPanel Childpanel){
        if(ContentFrame != null){
            ContainerPanel.remove(ContentFrame);
            ContentFrame = null;
        }
        ContentFrame = Childpanel;
        ContainerPanel.setLayout(new GridLayout(1, 1));
        ContainerPanel.add(Childpanel);
        ContainerPanel.setBorder(null);
        ContainerPanel.setBorder(BorderFactory.createLineBorder(Color.GRAY, 0));
        //Childpanel.refresh();
    }
    private void UserManagerMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManagerMenuBtnActionPerformed
        // TODO add your handling code here:
        //UserManagerInternalFrame Inframe = new UserManagerInternalFrame();
        UserManager Childpanel = new UserManager();
        ShowChildPanel(Childpanel);
    }//GEN-LAST:event_UserManagerMenuBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Bạn muốn thoát khỏi chương trình?", "Xác nhận thoát!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (input == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void StudentManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentManagerBtnActionPerformed
        // TODO add your handling code here:
        StudentManager Childpanel = new StudentManager();
        ShowChildPanel(Childpanel);
    }//GEN-LAST:event_StudentManagerBtnActionPerformed

    private void ChangePassMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassMenuBtnActionPerformed
        // TODO add your handling code here:
         PasswdChange Childpanel = new PasswdChange(UsernameString);
        ShowChildPanel(Childpanel);
    }//GEN-LAST:event_ChangePassMenuBtnActionPerformed

    private void ClassManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassManagerBtnActionPerformed
        // TODO add your handling code here:
        ClassManager Childpanel = new ClassManager();
        ShowChildPanel(Childpanel);
    }//GEN-LAST:event_ClassManagerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new MainFormSwing().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ChangePassMenuBtn;
    private javax.swing.JMenuItem ClassManagerBtn;
    private javax.swing.JPanel ContainerPanel;
    private javax.swing.JMenuItem ExitBtn;
    private javax.swing.JMenuBar HeaderNav;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JMenu ManageMenu;
    private javax.swing.JMenuItem StudentManagerBtn;
    private javax.swing.JMenu SystemMenu;
    private javax.swing.JMenuItem UserManagerMenuBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel userRoleLabel;
    private javax.swing.JLabel usernamelabel;
    // End of variables declaration//GEN-END:variables
}
