/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package management;
import quanlysv.connect;
import quanlysv.Program;
import Interface.quanlysinhvien;
import Interface.changeclass;
import Interface.quanlytaikhoan;

import java.awt.Color;
import java.awt.GridLayout;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



import java.awt.Color;
import java.awt.GridLayout;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Huy Laptop
 */
public class mainform extends javax.swing.JFrame {

    /**
     * Creates new form mainform
     */
   

      public static String UsernameString;
    public mainform(String UsernameString, boolean UserIsAdmin) {
        initComponents();
        mainform.UsernameString = UsernameString;
        usernamelabel.setText(mainform.UsernameString);
        UserManagerMenuBtn.setEnabled(UserIsAdmin);
        UserManagerMenuBtn.setVisible(UserIsAdmin);
        if(UserIsAdmin){
            userRoleLabel.setText("Quản trị viên(Admin)");
        }else{
            userRoleLabel.setText("Người dùng(User)");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        userRoleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ContainerPanel = new javax.swing.JPanel();
        HeaderNav = new javax.swing.JMenuBar();
        SystemMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        UserManagerMenuBtn = new javax.swing.JMenuItem();
        ChangePassMenuBtn = new javax.swing.JMenuItem();
        ExitBtn = new javax.swing.JMenuItem();
        ManageMenu = new javax.swing.JMenu();
        btnquanlysinhvien = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderPanel.setBackground(new java.awt.Color(102, 255, 102));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(900, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("User:");

        usernamelabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        usernamelabel.setText("username");

        userRoleLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        userRoleLabel.setText("Rolename");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Quyền:");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernamelabel)
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userRoleLabel)
                .addGap(52, 52, 52))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(userRoleLabel))
                    .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(usernamelabel)))
                .addContainerGap())
        );

        ContainerPanel.setAutoscrolls(true);
        ContainerPanel.setPreferredSize(new java.awt.Dimension(900, 500));

        javax.swing.GroupLayout ContainerPanelLayout = new javax.swing.GroupLayout(ContainerPanel);
        ContainerPanel.setLayout(ContainerPanelLayout);
        ContainerPanelLayout.setHorizontalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContainerPanelLayout.setVerticalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        HeaderNav.setBackground(new java.awt.Color(102, 102, 102));
        HeaderNav.setForeground(new java.awt.Color(15, 14, 14));
        HeaderNav.setMargin(new java.awt.Insets(0, 16, 0, 16));
        HeaderNav.setMinimumSize(new java.awt.Dimension(136, 36));
        HeaderNav.setPreferredSize(new java.awt.Dimension(136, 36));

        SystemMenu.setBackground(new java.awt.Color(153, 153, 153));
        SystemMenu.setForeground(new java.awt.Color(255, 255, 255));
        SystemMenu.setText("Hệ thống");
        SystemMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        SystemMenu.setMargin(new java.awt.Insets(0, 48, 0, 48));

        jMenu1.setText("jMenu1");
        SystemMenu.add(jMenu1);

        UserManagerMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        UserManagerMenuBtn.setText("Quản lý người dùng");
        UserManagerMenuBtn.setMargin(new java.awt.Insets(0, 24, 0, 24));
        UserManagerMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManagerMenuBtnActionPerformed(evt);
            }
        });
        SystemMenu.add(UserManagerMenuBtn);

        ChangePassMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ChangePassMenuBtn.setText("Đổi mật khẩu");
        ChangePassMenuBtn.setMargin(new java.awt.Insets(0, 24, 0, 24));
        ChangePassMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassMenuBtnActionPerformed(evt);
            }
        });
        SystemMenu.add(ChangePassMenuBtn);

        ExitBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ExitBtn.setText("Thoát");
        ExitBtn.setMargin(new java.awt.Insets(0, 24, 0, 24));
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        SystemMenu.add(ExitBtn);

        ManageMenu.setBackground(new java.awt.Color(153, 153, 153));
        ManageMenu.setText("Quản lý");
        ManageMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ManageMenu.setMargin(new java.awt.Insets(0, 48, 0, 48));

        btnquanlysinhvien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnquanlysinhvien.setText("Thông tin sinh viên");
        btnquanlysinhvien.setMargin(new java.awt.Insets(0, 24, 0, 24));
        btnquanlysinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlysinhvienActionPerformed(evt);
            }
        });
        ManageMenu.add(btnquanlysinhvien);

        SystemMenu.add(ManageMenu);

        HeaderNav.add(SystemMenu);

        setJMenuBar(HeaderNav);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
            .addComponent(ContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public void FillTable(JTable table, String MysqltableName) throws ClassNotFoundException, SQLException
    {
        connect conn = new connect();
        ResultSet rs = conn.getData(MysqltableName);
        while(table.getRowCount() > 0) 
        {
            //JOptionPane.showMessageDialog(null, table.getRowCount());
            ((DefaultTableModel) table.getModel()).setRowCount(0);
            //((DefaultTableModel) table.getModel()).removeRow(0);
        }
        int columns = rs.getMetaData().getColumnCount();
        while(rs.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                row[i - 1] = rs.getObject(i);
            }
            ((DefaultTableModel) table.getModel()).insertRow(rs.getRow()-1,row);
        }
    }

    JPanel ContentFrame = null;
    private void ShowChildPanel(JPanel Childpanel){
        if(ContentFrame != null){
            ContainerPanel.remove(ContentFrame);
            ContentFrame = null;
        }
        ContentFrame = Childpanel;
        ContainerPanel.setLayout(new GridLayout(1, 1));
        ContainerPanel.add(Childpanel);
        ContainerPanel.setBorder(null);
        ContainerPanel.setBorder(BorderFactory.createLineBorder(Color.GRAY, 0));
        //Childpanel.refresh();
    }
    private void UserManagerMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManagerMenuBtnActionPerformed

        //    quanlycanbo Inframe = new quanlycanbo();
        System.out.println("Chào mừng bạn đến với giao diện quản lý tài khoản người dùng");
        JOptionPane.showMessageDialog(null, "Quản lý tài khoản người dùng");
        quanlytaikhoan a = new quanlytaikhoan();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UserManagerMenuBtnActionPerformed

    private void ChangePassMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassMenuBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Giao diên đổi mật khẩu tài khoản");
        JOptionPane.showMessageDialog(null, "Đổi mật khẩu tài khoản");
        changeclass a = new changeclass(UsernameString);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ChangePassMenuBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Bạn muốn thoát khỏi chương trình?", "Xác nhận thoát!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (input == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void btnquanlysinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlysinhvienActionPerformed
        // TODO add your handling code here:
        System.out.println("Chào mừng bạn đến với giao diện quản lý thông tin lớp học");
        JOptionPane.showMessageDialog(null, "Quản lý thông tin lớp học");
        quanlysinhvien b = new quanlysinhvien();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnquanlysinhvienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ChangePassMenuBtn;
    private javax.swing.JPanel ContainerPanel;
    private javax.swing.JMenuItem ExitBtn;
    private javax.swing.JMenuBar HeaderNav;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JMenu ManageMenu;
    private javax.swing.JMenu SystemMenu;
    private javax.swing.JMenuItem UserManagerMenuBtn;
    private javax.swing.JMenuItem btnquanlysinhvien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel userRoleLabel;
    private javax.swing.JLabel usernamelabel;
    // End of variables declaration//GEN-END:variables
}
