/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package managementinterface;
import quanlycanbo.connect;
import java.sql.SQLException;
import static java.time.zone.ZoneRulesProvider.refresh;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import javax.swing.JPanel;
import javax.swing.text.TabableView;
import quanlycanbo.Program;
/**
 *
 * @author Huy Laptop
 */
public final class canbo extends javax.swing.JFrame {

    /**
     * Creates new form canbo
     */
    public canbo() {
        initComponents();
           
        txtFieldID.addKeyListener(quanlycanbo.Program.Onlynumber);
        txtFieldDay.addKeyListener(quanlycanbo.Program.Onlynumber);
        txtFieldMonth.addKeyListener(quanlycanbo.Program.Onlynumber);
        txtFieldYear.addKeyListener(quanlycanbo.Program.Onlynumber);
        try {
            FillClassIDCombobox();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(canbo.class.getName()).log(Level.SEVERE, null, ex);
        }
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldethnic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldName = new javax.swing.JTextField();
        txtFieldKeyword = new javax.swing.JTextField();
        BtnAdd = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnSearch = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFieldID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radiobtnMale = new javax.swing.JRadioButton();
        radiobtnFemale = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        comboboxphongban = new javax.swing.JComboBox<>();
        txtFieldDay = new javax.swing.JTextField();
        txtFieldMonth = new javax.swing.JTextField();
        txtFieldYear = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFieldaddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabledata = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtchucvu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btndau = new javax.swing.JButton();
        btnvedau = new javax.swing.JButton();
        btncuoi = new javax.swing.JButton();
        btnvecuoi = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(850, 490));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Phòng ban:");

        txtFieldethnic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tên cán bộ:");

        txtFieldName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtFieldKeyword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFieldKeyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldKeywordKeyPressed(evt);
            }
        });

        BtnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnAdd.setText("Thêm");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refreshBtn.setText("Làm mới");
        refreshBtn.setPreferredSize(new java.awt.Dimension(90, 25));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        BtnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnDelete.setText("Xoá");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnSearch.setText("Tìm kiếm");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        BtnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnEdit.setText("Sửa");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã cán bộ:");

        txtFieldID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Giới Tính:");

        radiobtnMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radiobtnMale.setText("Nam");

        radiobtnFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radiobtnFemale.setText("Nữ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(radiobtnMale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radiobtnFemale)
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobtnMale)
                    .addComponent(radiobtnFemale)))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Ngày Sinh:");

        comboboxphongban.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtFieldDay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFieldDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldDayFocusLost(evt);
            }
        });
        txtFieldDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldDayKeyPressed(evt);
            }
        });

        txtFieldMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFieldMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldMonthFocusLost(evt);
            }
        });
        txtFieldMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldMonthKeyPressed(evt);
            }
        });

        txtFieldYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFieldYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldYearKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Dân Tộc:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Quê quán:");

        txtFieldaddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFieldaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldaddressActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Tabledata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã cán bộ", "Tên cán bộ", "Mã phòng ban", "Giới tính", "Ngày sinh", "Dân tộc", "Quê quán", "Chức vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabledata.setRequestFocusEnabled(false);
        Tabledata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabledataMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabledata);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Chức vụ:");

        txtchucvu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nhập thông tin cần tìm:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("QUẢN LÝ CÁN BỘ");

        btndau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btndau.setText("|<");
        btndau.setName("btnnhieutrai"); // NOI18N
        btndau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndauActionPerformed(evt);
            }
        });

        btnvedau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnvedau.setText("<");
        btnvedau.setName("btntrai"); // NOI18N
        btnvedau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvedauActionPerformed(evt);
            }
        });

        btncuoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btncuoi.setText(">|");
        btncuoi.setName("btnnhieuphai"); // NOI18N
        btncuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuoiActionPerformed(evt);
            }
        });

        btnvecuoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnvecuoi.setText(">");
        btnvecuoi.setName("btnphai"); // NOI18N
        btnvecuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvecuoiActionPerformed(evt);
            }
        });

        btnthoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtFieldYear))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)
                                                .addGap(0, 14, Short.MAX_VALUE)))
                                        .addComponent(txtFieldethnic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtFieldaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(215, 215, 215))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboboxphongban, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndau)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnvedau, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnvecuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncuoi))
                    .addComponent(btnthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(356, 356, 356))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFieldethnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFieldaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSearch))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthoat))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(comboboxphongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAdd)
                            .addComponent(BtnEdit)
                            .addComponent(BtnDelete))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncuoi)
                            .addComponent(btnvecuoi)
                            .addComponent(btnvedau)
                            .addComponent(btndau))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void LimitLengthTxtField(JTextField txtfield, int Limit, java.awt.event.KeyEvent evt){
        if(txtfield.getText().length()>=Limit)
        {
            txtfield.setText(txtfield.getText().substring(0, Limit-1));
        }
    }
    final String OLD_FORMAT = "yyyy-MM-dd";
    final String NEW_FORMAT = "dd/MM/yyyy";
    
    public void FillClassIDCombobox() throws ClassNotFoundException, SQLException{
        connect conn = new connect();
        ResultSet rs = conn.getData("phongban");
        if(comboboxphongban.getItemCount() > 0){
            comboboxphongban.removeAllItems();
        }
        while(rs.next())
        {  
            comboboxphongban.addItem((String)rs.getString("mapb"));
        }
    }
      public void FillTable(JTable table, String MysqltableName) throws ClassNotFoundException, SQLException
    {
        connect conn = new connect();
         ResultSet rs = conn.getData(MysqltableName);
        while(table.getRowCount() > 0) 
        {
            //JOptionPane.showMessageDialog(null, table.getRowCount());
            ((DefaultTableModel) table.getModel()).setRowCount(0);
            //((DefaultTableModel) table.getModel()).removeRow(0);
        }
        int columns = rs.getMetaData().getColumnCount();
        while(rs.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                if(i == 4)
                {
                    if (rs.getBoolean(i)) {row[i - 1] = "Nam";}
                    else {row[i - 1] = "Nữ";}
                    continue;
                }
                if(i==5)
                {
                    SimpleDateFormat date = new SimpleDateFormat(OLD_FORMAT);
                    try {
                        Date datestr = null;
                        datestr = date.parse(rs.getString(i));
                        date.applyPattern(NEW_FORMAT);
                        row[i - 1] = date.format(datestr);
                    continue;
                    } catch (ParseException ex) {
                        Logger.getLogger(canbo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                row[i - 1] = rs.getObject(i);
            }
            ((DefaultTableModel) table.getModel()).insertRow(rs.getRow()-1,row);
        }
    }
    private void TabledataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabledataMousePressed
        // TODO add your handling code here:
          txtFieldID.setText(Integer.toString((int)Tabledata.getValueAt(Tabledata.getSelectedRow() , 0)));
        txtFieldName.setText((String)Tabledata.getValueAt(Tabledata.getSelectedRow() , 1));
        comboboxphongban.setSelectedItem((String)Tabledata.getValueAt(Tabledata.getSelectedRow() , 2));
        if(Tabledata.getValueAt(Tabledata.getSelectedRow() , 3).equals("Nam")){
            radiobtnMale.setSelected(true);
        }else{
            radiobtnFemale.setSelected(true);
        }
        String datestring = (String)Tabledata.getValueAt(Tabledata.getSelectedRow(), 4);
        SimpleDateFormat datefomat = new SimpleDateFormat(NEW_FORMAT);
        Date date;
        try {
            date = datefomat.parse(datestring);
            txtFieldDay.setText(Integer.toString(date.getDate()));
            txtFieldMonth.setText(Integer.toString(date.getMonth()+1));
            txtFieldYear.setText(Integer.toString(date.getYear()+1900));
        } catch (ParseException ex) {
            Logger.getLogger(canbo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtFieldethnic.setText((String)Tabledata.getValueAt(Tabledata.getSelectedRow() , 5));
        txtFieldaddress.setText((String)Tabledata.getValueAt(Tabledata.getSelectedRow() , 6));
        txtchucvu.setText((String)Tabledata.getValueAt(Tabledata.getSelectedRow() , 7));
       
    }//GEN-LAST:event_TabledataMousePressed

    private void txtFieldKeywordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldKeywordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnSearchActionPerformed(null);
        }
    }//GEN-LAST:event_txtFieldKeywordKeyPressed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        int ID = Integer.parseInt(txtFieldID.getText().trim());
        String Name = txtFieldName.getText().trim();
        String dt = txtFieldethnic.getText().trim();
        int Gender = (radiobtnMale.isSelected()) ? 1 : 0;
        String ClassID = (String)comboboxphongban.getSelectedItem();
        String date = txtFieldYear.getText().trim() +"/"+txtFieldMonth.getText().trim()+"/"+txtFieldDay.getText().trim();
        String address = txtFieldaddress.getText().trim();
        String chucvu = txtchucvu.getText().trim();
        try {
            connect conn = new connect();
            conn.StudentInsert(ID, Name, ClassID, Gender, date, dt, address,chucvu);
            refresh();
        } catch (ClassNotFoundException | SQLException ex) {
            String exp = ex.getMessage();
            if(exp.contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Mã cán bộ đã tồn tại!");
            }
            Logger.getLogger(canbo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAddActionPerformed
 public void refresh(){
        refreshBtnActionPerformed(null);
    };
    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        try {
            // TODO add your handling code here:
            FillTable(Tabledata, "canbo");
        } catch (ClassNotFoundException | SQLException ex) {
            
            Logger.getLogger(canbo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshBtnActionPerformed
 
    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        String ID = txtFieldID.getText().trim();
        try {
            connect conn = new connect();
            conn.Delete(ID, "canbo", "macb");
            refreshBtnActionPerformed(null);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(canbo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        // TODO add your handling code here:
        String keyword = txtFieldKeyword.getText().trim();
        if(keyword.isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập từ khoá");
            txtFieldKeyword.requestFocus();
        }else{
            try {
                FillTable(Tabledata,"canbo where hoten LIKE '%"+keyword+"%' OR quequan LIKE '%"+keyword+"%' OR dantoc LIKE '%"+keyword+"%'OR chucvu LIKE '%"+keyword+"%'");
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(canbo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
        int ID = Integer.parseInt(txtFieldID.getText().trim());
        String Name = txtFieldName.getText().trim();
        String dt = txtFieldethnic.getText().trim();
        int Gender = (radiobtnMale.isSelected()) ? 1 : 0;
        String ClassID = (String)comboboxphongban.getSelectedItem();
        String date = txtFieldYear.getText().trim() +"/"+txtFieldMonth.getText().trim()+"/"+txtFieldDay.getText().trim();
        String address = txtFieldaddress.getText().trim();
        String chucvu = txtchucvu.getText().trim();
        try {
            connect conn = new connect();
            conn.StudentUpdate(ID, Name, ClassID, Gender, date, dt, address,chucvu);
            refresh();
        } catch (ClassNotFoundException | SQLException ex) {
            String exp = ex.getMessage();
            if(exp.contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Mã cán bộ đã tồn tại!");
            }
            Logger.getLogger(canbo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void txtFieldDayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldDayFocusLost
        // TODO add your handling code here:
        if(Integer.parseInt(txtFieldDay.getText().trim()) > 31){
            txtFieldDay.setText("31");
        }
    }//GEN-LAST:event_txtFieldDayFocusLost

    private void txtFieldDayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldDayKeyPressed
        // TODO add your handling code here:
        LimitLengthTxtField(txtFieldDay, 2, evt);
    }//GEN-LAST:event_txtFieldDayKeyPressed

    private void txtFieldMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldMonthFocusLost
        // TODO add your handling code here:
        if(Integer.parseInt(txtFieldMonth.getText().trim()) > 12){
            txtFieldMonth.setText("12");
        }
    }//GEN-LAST:event_txtFieldMonthFocusLost

    private void txtFieldMonthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldMonthKeyPressed
        // TODO add your handling code here:
        LimitLengthTxtField(txtFieldMonth, 2, evt);
    }//GEN-LAST:event_txtFieldMonthKeyPressed

    private void txtFieldYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldYearKeyPressed
        // TODO add your handling code here:
        LimitLengthTxtField(txtFieldYear, 4, evt);
    }//GEN-LAST:event_txtFieldYearKeyPressed

    private void txtFieldaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldaddressActionPerformed

    private void btndauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndauActionPerformed
        if(Tabledata.getRowCount()>0)
        {
            Tabledata.getSelectionModel().setSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_btndauActionPerformed

    private void btnvedauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvedauActionPerformed
        int rowSelected=Tabledata.getSelectedRow();
        if(rowSelected>0){
            rowSelected --;
            Tabledata.getSelectionModel().setSelectionInterval(rowSelected, rowSelected);

        }
    }//GEN-LAST:event_btnvedauActionPerformed

    private void btncuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuoiActionPerformed
        if(Tabledata.getRowCount()>0){
            int lastRowIndex=Tabledata.getRowCount()-1;
            Tabledata.getSelectionModel().setSelectionInterval(lastRowIndex, lastRowIndex);
        }
    }//GEN-LAST:event_btncuoiActionPerformed

    private void btnvecuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvecuoiActionPerformed
        int rowSelected=Tabledata.getSelectedRow();
        if(rowSelected<Tabledata.getRowCount()-1){
            rowSelected++;
            Tabledata.getSelectionModel().setSelectionInterval(rowSelected, rowSelected);
        }
    }//GEN-LAST:event_btnvecuoiActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Bạn muốn thoát chương trình này?");
        System.out.println("option: " + option);

        if (option == 0) {
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_btnthoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(canbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(canbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(canbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(canbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new canbo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JTable Tabledata;
    private javax.swing.JButton btncuoi;
    private javax.swing.JButton btndau;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnvecuoi;
    private javax.swing.JButton btnvedau;
    private javax.swing.JComboBox<String> comboboxphongban;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiobtnFemale;
    private javax.swing.JRadioButton radiobtnMale;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField txtFieldDay;
    private javax.swing.JTextField txtFieldID;
    private javax.swing.JTextField txtFieldKeyword;
    private javax.swing.JTextField txtFieldMonth;
    private javax.swing.JTextField txtFieldName;
    private javax.swing.JTextField txtFieldYear;
    private javax.swing.JTextField txtFieldaddress;
    private javax.swing.JTextField txtFieldethnic;
    private javax.swing.JTextField txtchucvu;
    // End of variables declaration//GEN-END:variables

   

   
}
