/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package managementinterface;

import GeneralManagement.MainForm;
import static GeneralManagement.MainForm.UsernameString;
import java.awt.event.KeyEvent;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import quanlycanbo.connect;
import javax.swing.JPanel;
import quanlycanbo.Program;
import GeneralManagement.MainForm;
/**
 *
 * @author Huy Laptop
 */
public class PasswdChange extends javax.swing.JFrame {

    /**
     * Creates new form PasswdChange
     */
   String UsernameString;
    public PasswdChange(String UsernameString) {
        this.UsernameString = UsernameString;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSubmit = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        checkboxShowOld = new javax.swing.JCheckBox();
        checkboxShowNew = new javax.swing.JCheckBox();
        checkboxShowConfirm = new javax.swing.JCheckBox();
        txtFieldOldpass = new javax.swing.JPasswordField();
        txtFieldNewpass = new javax.swing.JPasswordField();
        txtFieldConfirm = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnthoat1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnSubmit.setText("Thay đổi");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });

        BtnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnClear.setText("Nhập lại");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mật khẩu hiện tại:");

        checkboxShowOld.setText("Ẩn/Hiện");
        checkboxShowOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxShowOldActionPerformed(evt);
            }
        });

        checkboxShowNew.setText("Ẩn/Hiện");
        checkboxShowNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxShowNewActionPerformed(evt);
            }
        });

        checkboxShowConfirm.setText("Ẩn/Hiện");
        checkboxShowConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxShowConfirmActionPerformed(evt);
            }
        });

        txtFieldOldpass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtFieldOldpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldOldpassKeyPressed(evt);
            }
        });

        txtFieldNewpass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtFieldNewpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldNewpassKeyPressed(evt);
            }
        });

        txtFieldConfirm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtFieldConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldConfirmKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nhập lại mật khẩu mới:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Mật khẩu mới:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ĐỔI MẬT KHẨU");

        btnthoat1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnthoat1.setText("Thoát");
        btnthoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(290, 290, 290))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldOldpass, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(txtFieldNewpass)
                                    .addComponent(txtFieldConfirm))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkboxShowOld)
                                    .addComponent(checkboxShowNew)
                                    .addComponent(checkboxShowConfirm)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(189, 189, 189))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkboxShowOld)
                    .addComponent(txtFieldOldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(checkboxShowNew)
                    .addComponent(txtFieldNewpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(checkboxShowConfirm)
                    .addComponent(txtFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSubmit)
                    .addComponent(BtnClear))
                .addGap(27, 27, 27)
                .addComponent(btnthoat1)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void EnterCheck(KeyEvent e){
        if(e.getKeyCode() == KeyEvent.VK_ENTER) {
          BtnSubmitActionPerformed(null);
        }
    }
    private boolean validator(){
        String newPass = txtFieldNewpass.getText().trim();
        String Confirm = txtFieldConfirm.getText().trim();
        if (!(newPass.isEmpty() || Confirm.isEmpty())) {
            if(newPass.equals(Confirm)) {
                return true;
            }else {
                JOptionPane.showMessageDialog(null, "mật khẩu mới không trùng khớp!");
                return false;
            }
        }
        JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ các trường!");
        return false;
    }
    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
        // TODO add your handling code here:
                                              
        // TODO add your handling code here:
        if(!validator()){
            txtFieldConfirm.requestFocus();
            return;
        }
        String CurrentPass = txtFieldOldpass.getText().trim();
        String newPass = txtFieldNewpass.getText().trim();
        try {
            connect conn = new connect();
            ResultSet rs = conn.getData("user where username= '"+ UsernameString +"' and password = '"+ CurrentPass +"'");
            if(rs.next()){
                conn.UserUpdatePasswd(Integer.parseInt(rs.getString("id")), newPass);
                JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công!");
                BtnClearActionPerformed(evt);
            }else{
                JOptionPane.showMessageDialog(null, "Mật khẩu hiện tại không chính xác!");
                txtFieldOldpass.requestFocus();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            java.util.logging.Logger.getLogger(PasswdChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_BtnSubmitActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        // TODO add your handling code here:
        txtFieldOldpass.setText("");
        txtFieldNewpass.setText("");
        txtFieldConfirm.setText("");

    }//GEN-LAST:event_BtnClearActionPerformed

    private void checkboxShowOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxShowOldActionPerformed
        // TODO add your handling code here:
       quanlycanbo.Program.ShowHidePasswd(txtFieldOldpass, checkboxShowOld);
    }//GEN-LAST:event_checkboxShowOldActionPerformed

    private void checkboxShowNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxShowNewActionPerformed
        // TODO add your handling code here:
        quanlycanbo.Program.ShowHidePasswd(txtFieldNewpass, checkboxShowNew);
    }//GEN-LAST:event_checkboxShowNewActionPerformed

    private void checkboxShowConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxShowConfirmActionPerformed
        // TODO add your handling code here:
        quanlycanbo.Program.ShowHidePasswd(txtFieldConfirm, checkboxShowConfirm);
    }//GEN-LAST:event_checkboxShowConfirmActionPerformed

    private void txtFieldOldpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldOldpassKeyPressed
        // TODO add your handling code here:
        EnterCheck(evt);
    }//GEN-LAST:event_txtFieldOldpassKeyPressed

    private void txtFieldNewpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldNewpassKeyPressed
        // TODO add your handling code here:
        EnterCheck(evt);
    }//GEN-LAST:event_txtFieldNewpassKeyPressed

    private void txtFieldConfirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldConfirmKeyPressed
        // TODO add your handling code here:
        EnterCheck(evt);
    }//GEN-LAST:event_txtFieldConfirmKeyPressed

    private void btnthoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoat1ActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Bạn muốn thoát chương trình này?");
        System.out.println("option: " + option);

        if (option == 0) {
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_btnthoat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswdChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswdChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswdChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswdChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new PasswdChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JButton btnthoat1;
    private javax.swing.JCheckBox checkboxShowConfirm;
    private javax.swing.JCheckBox checkboxShowNew;
    private javax.swing.JCheckBox checkboxShowOld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtFieldConfirm;
    private javax.swing.JPasswordField txtFieldNewpass;
    private javax.swing.JPasswordField txtFieldOldpass;
    // End of variables declaration//GEN-END:variables

   
}
