/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import quanlysv.connect;
import quanlysv.Program;
import Interface.quanlysinhvien;
import Interface.changeclass;
import Interface.quanlytaikhoan;

import java.awt.Color;
import java.awt.GridLayout;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.*;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import static java.time.zone.ZoneRulesProvider.refresh;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import management.mainform;
/**
/**
 *
 * @author Huy Laptop
 */
public final class quanlysinhvien extends javax.swing.JFrame {

   
    public quanlysinhvien() {
        initComponents();
        txtFieldID.addKeyListener(quanlysv.Program.Onlynumber);
        txtFieldDay.addKeyListener(quanlysv.Program.Onlynumber);
        txtFieldMonth.addKeyListener(quanlysv.Program.Onlynumber);
        txtFieldYear.addKeyListener(quanlysv.Program.Onlynumber);
        try {
            FillClassIDCombobox();
        } catch (ClassNotFoundException | SQLException ex) {
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        refresh();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnDelete = new javax.swing.JButton();
        txtFieldDay = new javax.swing.JTextField();
        BtnSearch = new javax.swing.JButton();
        txtFieldMonth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtnEdit = new javax.swing.JButton();
        txtFieldYear = new javax.swing.JTextField();
        txtFieldethnic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFieldID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabledata = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtFieldaddress = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        radiobtnMale = new javax.swing.JRadioButton();
        radiobtnFemale = new javax.swing.JRadioButton();
        txtFieldName = new javax.swing.JTextField();
        txtFieldKeyword = new javax.swing.JTextField();
        BtnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        txtmalop = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnthoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("hinh");

        BtnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnDelete.setText("Xoá");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        txtFieldDay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFieldDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldDayFocusLost(evt);
            }
        });
        txtFieldDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldDayKeyPressed(evt);
            }
        });

        BtnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnSearch.setText("Tìm kiếm");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        txtFieldMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFieldMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldMonthFocusLost(evt);
            }
        });
        txtFieldMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldMonthKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mã Lớp:");

        BtnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnEdit.setText("Sửa");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        txtFieldYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFieldYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldYearKeyPressed(evt);
            }
        });

        txtFieldethnic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã sinh viên:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Dân Tộc:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tên sinh viên:");

        txtFieldID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Địa Chỉ:");

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Tabledata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "Mã Lớp", "Giới Tính", "Ngày Sinh", "Dân Tộc", "Quê Quán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabledata.setRequestFocusEnabled(false);
        Tabledata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabledataMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabledata);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Giới Tính:");

        txtFieldaddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        radiobtnMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radiobtnMale.setText("Nam");

        radiobtnFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radiobtnFemale.setText("Nữ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(radiobtnMale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radiobtnFemale)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobtnMale)
                    .addComponent(radiobtnFemale)))
        );

        txtFieldName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtFieldKeyword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFieldKeyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldKeywordKeyPressed(evt);
            }
        });

        BtnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnAdd.setText("Thêm");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Ngày Sinh:");

        refreshBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refreshBtn.setText("Làm mới");
        refreshBtn.setPreferredSize(new java.awt.Dimension(90, 25));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        txtmalop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("QUẢN LÝ SINH VIÊN");

        btnthoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFieldYear))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldethnic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmalop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtFieldaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(BtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnthoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFieldethnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFieldaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAdd)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnEdit)
                                    .addComponent(txtmalop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnSearch)
                                    .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addComponent(btnthoat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public void LimitLengthTxtField(JTextField txtfield, int Limit, java.awt.event.KeyEvent evt){
        if(txtfield.getText().length()>=Limit)
        {
            txtfield.setText(txtfield.getText().substring(0, Limit-1));
        }
    }
    public void FillTable(JTable table, String MysqltableName) throws ClassNotFoundException, SQLException
    {
        connect conn = new connect();
        ResultSet rs = conn.getData(MysqltableName);
        while(table.getRowCount() > 0) 
        {
            //JOptionPane.showMessageDialog(null, table.getRowCount());
            ((DefaultTableModel) table.getModel()).setRowCount(0);
            //((DefaultTableModel) table.getModel()).removeRow(0);
        }
        int columns = rs.getMetaData().getColumnCount();
        while(rs.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                if(i == 4)
                {
                    if (rs.getBoolean(i)) {row[i - 1] = "Nam";}
                    else {row[i - 1] = "Nữ";}
                    continue;
                }
                if(i==5)
                {
                    SimpleDateFormat date = new SimpleDateFormat(OLD_FORMAT);
                    try {
                        java.util.Date datestr = null;
                        datestr = date.parse(rs.getString(i));
                        date.applyPattern(NEW_FORMAT);
                        row[i - 1] = date.format(datestr);
                    continue;
                    } catch (ParseException ex) {
                        java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                }
                row[i - 1] = rs.getObject(i);
            }
            ((DefaultTableModel) table.getModel()).insertRow(rs.getRow()-1,row);
        }
    }
    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        String ID = txtFieldID.getText().trim();
        try {
            connect conn = new connect();
            conn.Delete(ID, "sinhvien", "masv");
            refreshBtnActionPerformed(null);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void txtFieldDayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldDayFocusLost
        // TODO add your handling code here:
        if(Integer.parseInt(txtFieldDay.getText().trim()) > 31){
            txtFieldDay.setText("31");
        }
    }//GEN-LAST:event_txtFieldDayFocusLost

    private void txtFieldDayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldDayKeyPressed
        // TODO add your handling code here:
        LimitLengthTxtField(txtFieldDay, 2, evt);
    }//GEN-LAST:event_txtFieldDayKeyPressed

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        // TODO add your handling code here:
          String keyword = txtFieldKeyword.getText().trim();
        if(keyword.isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập từ khoá");
            txtFieldKeyword.requestFocus();
        }else{
            try {
                FillTable(Tabledata,"sinhvien where hoten LIKE '%"+keyword+"%'OR malop LIKE '%"+keyword+"%' OR quequan LIKE '%"+keyword+"%' OR dantoc LIKE '%"+keyword+"%'");
            } catch (ClassNotFoundException | SQLException ex) {
                java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void txtFieldMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldMonthFocusLost
        // TODO add your handling code here:
        if(Integer.parseInt(txtFieldMonth.getText().trim()) > 12){
            txtFieldMonth.setText("12");
        }
    }//GEN-LAST:event_txtFieldMonthFocusLost

    private void txtFieldMonthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldMonthKeyPressed
        // TODO add your handling code here:
        LimitLengthTxtField(txtFieldMonth, 2, evt);
    }//GEN-LAST:event_txtFieldMonthKeyPressed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
       int ID = Integer.parseInt(txtFieldID.getText().trim());
        String Name = txtFieldName.getText().trim();
        String dt = txtFieldethnic.getText().trim();
        int Gender = (radiobtnMale.isSelected()) ? 1 : 0;
        String ClassID = txtmalop.getText().trim();
        String date = txtFieldYear.getText().trim() +"/"+txtFieldMonth.getText().trim()+"/"+txtFieldDay.getText().trim();
        String address = txtFieldaddress.getText().trim();
        try {
            connect conn = new connect();
            conn.StudentUpdate(ID, Name, ClassID, Gender, date, dt, address);
            refresh();
        } catch (ClassNotFoundException | SQLException ex) {
            String exp = ex.getMessage();
            if(exp.contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Mã học sinh đã tồn tại!");
            }
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void txtFieldYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldYearKeyPressed
        // TODO add your handling code here:
        LimitLengthTxtField(txtFieldYear, 4, evt);
    }//GEN-LAST:event_txtFieldYearKeyPressed

    private void TabledataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabledataMousePressed
        //TODO add your handling code here:
       txtFieldID.setText(Integer.toString((int)Tabledata.getValueAt(Tabledata.getSelectedRow() , 0)));
        txtFieldName.setText((String)Tabledata.getValueAt(Tabledata.getSelectedRow() , 1));
       txtmalop.setText((String)Tabledata.getValueAt(Tabledata.getSelectedRow() , 2));
        if(Tabledata.getValueAt(Tabledata.getSelectedRow() , 3).equals("Nam")){
            radiobtnMale.setSelected(true);
        }else{
            radiobtnFemale.setSelected(true);
        }
        String datestring = (String)Tabledata.getValueAt(Tabledata.getSelectedRow(), 4);
        SimpleDateFormat datefomat = new SimpleDateFormat(NEW_FORMAT);
        java.util.Date date;
        try {
            date = datefomat.parse(datestring);
            txtFieldDay.setText(Integer.toString(date.getDate()));
            txtFieldMonth.setText(Integer.toString(date.getMonth()+1));
            txtFieldYear.setText(Integer.toString(date.getYear()+1900));
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        txtFieldethnic.setText((String)Tabledata.getValueAt(Tabledata.getSelectedRow() , 5));
        txtFieldaddress.setText((String)Tabledata.getValueAt(Tabledata.getSelectedRow() , 6));
    }//GEN-LAST:event_TabledataMousePressed

    private void txtFieldKeywordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldKeywordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnSearchActionPerformed(null);
        }
    }//GEN-LAST:event_txtFieldKeywordKeyPressed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        int ID = Integer.parseInt(txtFieldID.getText().trim());
        String Name = txtFieldName.getText().trim();
        String dt = txtFieldethnic.getText().trim();
        int Gender = (radiobtnMale.isSelected()) ? 1 : 0;
        String classid = txtmalop.getText().trim();
        String date = txtFieldYear.getText().trim() +"/"+txtFieldMonth.getText().trim()+"/"+txtFieldDay.getText().trim();
        String address = txtFieldaddress.getText().trim();
        try {
            connect conn = new connect();
            conn.StudentInsert(ID, Name, classid, Gender, date, dt, address);
            refresh();
        } catch (ClassNotFoundException | SQLException ex) {
            String exp = ex.getMessage();
            if(exp.contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Mã học sinh đã tồn tại!");
            }
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAddActionPerformed
    final String OLD_FORMAT = "yyyy-MM-dd";
    final String NEW_FORMAT = "dd/MM/yyyy";
    
    public void FillClassIDCombobox() throws ClassNotFoundException, SQLException{
//        connect conn = new connect();
//        ResultSet rs = conn.getData("class");
//        if(comboboxClass.getItemCount() > 0){
//            comboboxClass.removeAllItems();
//        }
//        while(rs.next())
//        {  
//            comboboxClass.addItem((String)rs.getString("malop"));
//        }
    }
     public void refresh(){
        refreshBtnActionPerformed(null);
    };
    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
       try {
            // TODO add your handling code here:
            FillTable(Tabledata, "sinhvien");
        } catch (ClassNotFoundException | SQLException ex) {
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnthoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlysinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new quanlysinhvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JTable Tabledata;
    private javax.swing.JButton btnthoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiobtnFemale;
    private javax.swing.JRadioButton radiobtnMale;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField txtFieldDay;
    private javax.swing.JTextField txtFieldID;
    private javax.swing.JTextField txtFieldKeyword;
    private javax.swing.JTextField txtFieldMonth;
    private javax.swing.JTextField txtFieldName;
    private javax.swing.JTextField txtFieldYear;
    private javax.swing.JTextField txtFieldaddress;
    private javax.swing.JTextField txtFieldethnic;
    private javax.swing.JTextField txtmalop;
    // End of variables declaration//GEN-END:variables

   
}
